name: Publish to ECR

on:
  push:
    paths:
      - 'studio/**'
  workflow_dispatch:

env:
  ECR_REGION: us-east-1
  ECR_IMG: supabase/studio

jobs:
  publish:
    name: Publish to ECR
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v1
        with:
          platforms: amd64,arm64

      - uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.ECR_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Create ECR Repo if not Exists
        uses: int128/create-ecr-repository-action@v1
        id: ecr
        with:
          repository: ${{ env.ECR_IMG }}

      - uses: docker/build-push-action@v2
        with:
          context: studio
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.ecr.outputs.repository-uri }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
